FROM rust:1.87-slim AS builder

WORKDIR /usr/src/linkify
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /usr/src/linkify/target/release/linkify /app/linkify

CMD ["./linkify"]