services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/linkify
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/linkify/target
    working_dir: /usr/src/linkify
    command: sleep infinity
volumes:
  cargo-cache:
  target-cache: